[supervisord]
nodaemon=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
stdout_logfile=/var/www/html/nginx.log
stderr_logfile=/var/www/html/nginx_error.log
autorestart=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
stdout_logfile=/var/www/html/php-fpm.log
stderr_logfile=/var/www/html/php-fpm_error.log
autorestart=true

[program:cron]
command=/usr/sbin/cron -f
stdout_logfile=/var/www/html/cron.log
stderr_logfile=/var/www/html/cron_error.log
autorestart=true

[program:moodle-cron]
command=/usr/local/bin/php /var/www/html/admin/cli/cron.php
stdout_logfile=/var/www/html/moodle-cron.log
stderr_logfile=/var/www/html/moodle-error.log
autorestart=true

[program:log-cleaner]
command=/bin/sh -c "echo '0 0 */30 * * rm -f /var/www/html/moodle-cron.log /var/www/html/moodle-error.log /var/www/html/supervisord.log /var/www/html/nginx.log /var/www/html/nginx_error.log /var/www/html/php-fpm.log /var/www/html/php-fpm_error.log /var/www/html/cron.log /var/www/html/cron_error.log' > /etc/cron.d/clean-logs && chmod 0644 /etc/cron.d/clean-logs && crontab /etc/cron.d/clean-logs && tail -f /dev/null"
stdout_logfile=/var/www/html/log-cleaner.log
stderr_logfile=/var/www/html/log-cleaner_error.log
autorestart=true